# Applying Naive Baye's Classifier on a Categorical Dataset

Naive bayes Equation<br>
\begin{equation}
 p(A|B) = \frac{P(B \cap A)}{p(B)}
\end{equation}
<br>
when we deal with applying naive bayes classifier on data which has categorical features then we cant use the normal pdf<br>
if this dataset the stalk root column has ? in the column so to fill such values with other values I have creates a sample<br>distribution from the stalk-root column (without ? values) and did a sampling from that so to fill up ? values<br>



In [294]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
import scipy.stats as s

In [244]:
data = pd.read_csv("mushrooms.csv")

In [245]:
data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [303]:
list(data.loc[5])

['e',
 'x',
 'y',
 'y',
 't',
 'a',
 'f',
 'c',
 'b',
 'n',
 'e',
 'c',
 's',
 's',
 'w',
 'w',
 'p',
 'w',
 'o',
 'p',
 'k',
 'n',
 'g']

In [246]:
data["stalk-root"]

0       e
1       c
2       c
3       e
4       e
5       c
6       c
7       c
8       e
9       c
10      c
11      c
12      c
13      e
14      e
15      e
16      e
17      e
18      e
19      e
20      c
21      e
22      c
23      c
24      c
25      e
26      c
27      c
28      e
29      b
       ..
8094    ?
8095    c
8096    ?
8097    ?
8098    ?
8099    ?
8100    ?
8101    ?
8102    ?
8103    ?
8104    ?
8105    ?
8106    ?
8107    ?
8108    ?
8109    ?
8110    ?
8111    ?
8112    ?
8113    ?
8114    c
8115    ?
8116    ?
8117    ?
8118    ?
8119    ?
8120    ?
8121    ?
8122    ?
8123    ?
Name: stalk-root, Length: 8124, dtype: object

In [247]:
missing_index = data[data["stalk-root"]=="?"].index

In [248]:
missing_index

Int64Index([3984, 4023, 4076, 4100, 4104, 4196, 4200, 4283, 4291, 4326,
            ...
            8113, 8115, 8116, 8117, 8118, 8119, 8120, 8121, 8122, 8123],
           dtype='int64', length=2480)

In [249]:
data["stalk-root"].replace(to_replace="?",value=np.NaN,inplace=True)

In [250]:
values_dict = dict()
for col in data.columns:
    values_dict[col]=data[col].unique()

In [251]:
values_dict

{'class': array(['p', 'e'], dtype=object),
 'cap-shape': array(['x', 'b', 's', 'f', 'k', 'c'], dtype=object),
 'cap-surface': array(['s', 'y', 'f', 'g'], dtype=object),
 'cap-color': array(['n', 'y', 'w', 'g', 'e', 'p', 'b', 'u', 'c', 'r'], dtype=object),
 'bruises': array(['t', 'f'], dtype=object),
 'odor': array(['p', 'a', 'l', 'n', 'f', 'c', 'y', 's', 'm'], dtype=object),
 'gill-attachment': array(['f', 'a'], dtype=object),
 'gill-spacing': array(['c', 'w'], dtype=object),
 'gill-size': array(['n', 'b'], dtype=object),
 'gill-color': array(['k', 'n', 'g', 'p', 'w', 'h', 'u', 'e', 'b', 'r', 'y', 'o'],
       dtype=object),
 'stalk-shape': array(['e', 't'], dtype=object),
 'stalk-root': array(['e', 'c', 'b', 'r', nan], dtype=object),
 'stalk-surface-above-ring': array(['s', 'f', 'k', 'y'], dtype=object),
 'stalk-surface-below-ring': array(['s', 'f', 'y', 'k'], dtype=object),
 'stalk-color-above-ring': array(['w', 'g', 'p', 'n', 'b', 'e', 'o', 'c', 'y'], dtype=object),
 'stalk-color-be

In [252]:
data["stalk-root"].value_counts()

b    3776
e    1120
c     556
r     192
Name: stalk-root, dtype: int64

In [253]:
freq_dist = dict((data["stalk-root"].value_counts())/data["stalk-root"].shape[0])

In [254]:
freq_dist

{'b': 0.464795667159035,
 'e': 0.137863121614968,
 'c': 0.06843919251600197,
 'r': 0.023633677991137372}

In [255]:
sample = np.random.multinomial(n=len(missing_index),pvals=list(freq_dist.values()))

In [256]:
sample

array([1158,  336,  168,  818])

In [257]:
generated_samples=[]
i=0
for no in freq_dist.keys():
    generated_samples = generated_samples +[no]*sample[i]
    i=i+1

In [258]:
generated_samples

['b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b',
 'b'

In [259]:
np.random.shuffle(generated_samples)

In [260]:
generated_samples

['e',
 'b',
 'r',
 'b',
 'r',
 'b',
 'b',
 'b',
 'b',
 'e',
 'r',
 'r',
 'b',
 'b',
 'r',
 'b',
 'b',
 'r',
 'r',
 'r',
 'r',
 'b',
 'r',
 'b',
 'b',
 'r',
 'b',
 'r',
 'b',
 'r',
 'r',
 'r',
 'e',
 'b',
 'b',
 'b',
 'b',
 'r',
 'b',
 'b',
 'b',
 'r',
 'e',
 'e',
 'r',
 'r',
 'r',
 'r',
 'b',
 'b',
 'e',
 'b',
 'r',
 'b',
 'r',
 'b',
 'r',
 'r',
 'r',
 'r',
 'c',
 'b',
 'e',
 'b',
 'r',
 'b',
 'b',
 'e',
 'b',
 'b',
 'r',
 'r',
 'r',
 'e',
 'b',
 'r',
 'b',
 'b',
 'b',
 'r',
 'c',
 'c',
 'e',
 'b',
 'b',
 'e',
 'b',
 'r',
 'r',
 'b',
 'b',
 'b',
 'r',
 'r',
 'r',
 'r',
 'r',
 'b',
 'r',
 'b',
 'r',
 'r',
 'r',
 'c',
 'e',
 'b',
 'r',
 'b',
 'b',
 'e',
 'e',
 'r',
 'r',
 'b',
 'b',
 'c',
 'b',
 'b',
 'r',
 'b',
 'e',
 'b',
 'b',
 'r',
 'r',
 'b',
 'r',
 'b',
 'e',
 'r',
 'r',
 'r',
 'r',
 'b',
 'b',
 'r',
 'b',
 'b',
 'e',
 'e',
 'c',
 'r',
 'b',
 'r',
 'r',
 'b',
 'e',
 'b',
 'r',
 'b',
 'b',
 'r',
 'r',
 'e',
 'b',
 'e',
 'r',
 'e',
 'r',
 'r',
 'b',
 'e',
 'e',
 'r',
 'b',
 'c',
 'b'

In [261]:
missing_data = dict(zip(missing_index,generated_samples))
missing_data

{3984: 'e',
 4023: 'b',
 4076: 'r',
 4100: 'b',
 4104: 'r',
 4196: 'b',
 4200: 'b',
 4283: 'b',
 4291: 'b',
 4326: 'e',
 4329: 'r',
 4331: 'r',
 4357: 'b',
 4376: 'b',
 4380: 'r',
 4396: 'b',
 4419: 'b',
 4429: 'r',
 4459: 'r',
 4461: 'r',
 4494: 'r',
 4497: 'b',
 4498: 'r',
 4519: 'b',
 4522: 'b',
 4533: 'r',
 4534: 'b',
 4557: 'r',
 4610: 'b',
 4611: 'r',
 4647: 'r',
 4662: 'r',
 4663: 'e',
 4673: 'b',
 4717: 'b',
 4722: 'b',
 4777: 'b',
 4801: 'r',
 4806: 'b',
 4812: 'b',
 4814: 'b',
 4817: 'r',
 4824: 'e',
 4826: 'e',
 4831: 'r',
 4844: 'r',
 4846: 'r',
 4858: 'r',
 4859: 'b',
 4860: 'b',
 4869: 'e',
 4871: 'b',
 4884: 'r',
 4888: 'b',
 4898: 'r',
 4899: 'b',
 4903: 'r',
 4904: 'r',
 4911: 'r',
 4926: 'r',
 4931: 'c',
 4938: 'b',
 4939: 'e',
 4945: 'b',
 4946: 'r',
 4951: 'b',
 4964: 'b',
 4965: 'e',
 4966: 'b',
 4984: 'b',
 4986: 'r',
 4993: 'r',
 4996: 'r',
 4999: 'e',
 5001: 'b',
 5005: 'r',
 5010: 'b',
 5015: 'b',
 5023: 'b',
 5041: 'r',
 5051: 'c',
 5052: 'c',
 5053: 'e',
 507

In [262]:
data["stalk-root"].fillna(value=missing_data,inplace=True)

In [263]:
data["stalk-root"].unique()

array(['e', 'c', 'b', 'r'], dtype=object)

After filling up the missing values from a random sample taken from stalk root column<br>
now dividing the data into 3 parts

In [264]:
train = 75
cv = 10
test = 15

In [265]:
Training_data = data.iloc[:int(len(data)*(train/100))]
Cross_validation_data = data.iloc[int(len(data)*(train/100)):int(len(data)*(train+cv/100)),]
Testing_data = data.iloc[int(len(data)*((train+cv)/100)):]

In [266]:
Training_data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [267]:
Cross_validation_data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
6093     p         f           y         n       f    f               f   
6094     p         f           s         e       f    y               f   
6095     p         f           s         e       f    f               f   
6096     p         x           y         e       f    f               f   
6097     p         f           s         n       f    y               f   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
6093            c         n          b  ...                        k   
6094            c         n          b  ...                        k   
6095            c         n          b  ...                        s   
6096            c         n          b  ...                        k   
6097            c         n          b  ...                        k   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
6093                      p                      p         p          w   
6094                      p                      w         p          w   
6095                      w                      p         p          w   
6096                      w                      w         p          w   
6097                      w                      p         p          w   

     ring-number ring-type spore-print-color population habitat  
6093           o         e                 w          v       l  
6094           o         e                 w          v       l  
6095           o         e                 w          v       l  
6096           o         e                 w          v       p  
6097           o         e                 w          v       p  

[5 rows x 23 columns]

In [268]:
Testing_data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
6905     e         b           s         n       f    n               a   
6906     e         k           s         g       f    n               f   
6907     e         x           f         g       f    n               f   
6908     p         x           s         n       f    s               f   
6909     p         k           y         e       f    f               f   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
6905            c         b          n  ...                        s   
6906            w         b          w  ...                        k   
6907            w         b          g  ...                        k   
6908            c         n          b  ...                        k   
6909            c         n          b  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
6905                      o                      o         p          n   
6906                      w                      w         p          w   
6907                      w                      w         p          w   
6908                      w                      p         p          w   
6909                      w                      w         p          w   

     ring-number ring-type spore-print-color population habitat  
6905           o         p                 y          c       l  
6906           t         p                 w          n       g  
6907           t         p                 w          s       g  
6908           o         e                 w          v       d  
6909           o         e                 w          v       p  

[5 rows x 23 columns]

In [269]:
values_dict_train = dict()
for col in data.columns:
    values_dict_train[col]=Training_data[col].unique()
    

In [270]:
values_dict_train

{'class': array(['p', 'e'], dtype=object),
 'cap-shape': array(['x', 'b', 's', 'f', 'k', 'c'], dtype=object),
 'cap-surface': array(['s', 'y', 'f', 'g'], dtype=object),
 'cap-color': array(['n', 'y', 'w', 'g', 'e', 'p', 'b', 'u', 'c', 'r'], dtype=object),
 'bruises': array(['t', 'f'], dtype=object),
 'odor': array(['p', 'a', 'l', 'n', 'f', 'c', 'y', 's'], dtype=object),
 'gill-attachment': array(['f', 'a'], dtype=object),
 'gill-spacing': array(['c', 'w'], dtype=object),
 'gill-size': array(['n', 'b'], dtype=object),
 'gill-color': array(['k', 'n', 'g', 'p', 'w', 'h', 'u', 'e', 'b', 'r', 'y', 'o'],
       dtype=object),
 'stalk-shape': array(['e', 't'], dtype=object),
 'stalk-root': array(['e', 'c', 'b', 'r'], dtype=object),
 'stalk-surface-above-ring': array(['s', 'f', 'k'], dtype=object),
 'stalk-surface-below-ring': array(['s', 'f', 'y', 'k'], dtype=object),
 'stalk-color-above-ring': array(['w', 'g', 'p', 'n', 'b', 'e', 'o'], dtype=object),
 'stalk-color-below-ring': array(['w', 'p

In [271]:
p_training_data = Training_data[Training_data["class"]=="p"]
e_training_data = Training_data[Training_data["class"]=="e"]

In [272]:
p_training_data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0      p         x           s         n       t    p               f   
3      p         x           y         w       t    p               f   
8      p         x           y         w       t    p               f   
13     p         x           y         w       t    p               f   
17     p         x           s         n       t    p               f   

   gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0             c         n          k  ...                        s   
3             c         n          n  ...                        s   
8             c         n          p  ...                        s   
13            c         n          k  ...                        s   
17            c         n          n  ...                        s   

   stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                       w                      w         p          w   
3                       w                      w         p          w   
8                       w                      w         p          w   
13                      w                      w         p          w   
17                      w                      w         p          w   

   ring-number ring-type spore-print-color population habitat  
0            o         p                 k          s       u  
3            o         p                 k          s       u  
8            o         p                 k          v       g  
13           o         p                 n          v       u  
17           o         p                 k          s       g  

[5 rows x 23 columns]

In [280]:
prior_p_train = p_training_data.shape[0]/Training_data.shape[0]
prior_e_train = e_training_data.shape[0]/Training_data.shape[0]
print(prior_p_train,prior_e_train)

0.3955358608238963 0.6044641391761038


when checking the values in e_training_data and in p_training_data we can see for the columns the unique value differs like the cap-shape column in training data has 6 unique values but in e_training_data and in p_training_data the unique value<br>for same column is diiefrent in no like cap_shape_e =[x,b,f,k] and cap_shape_p=[b,s,k,c,f] and the all values in <br>training data are =[x,b,s,f,k,c] so we can see that c in missing in cap_shape_e but we cant put the probability for <br>that as 0 beacuse it may not be present in e_training_data but might be present in cross validation data for class e for for such <br>condition we apply __LAPLACE SMOOTHENING__

In [273]:
def get_probabilites(new_data):
    final_dict=dict()
    for col in data.columns[1:]:
        if len(data[col].unique())!=len(new_data[col].unique()):
        
            not_present = set(data[col].unique())-set(new_data[col].unique())
            #print(list(not_present))
            sub_dict=dict()
            for no in list(not_present):
                sub_dict[no]=1/(len(new_data)+len(data[col].unique()))
            #print(sub_dict)
            dict1 = dict((new_data[col].value_counts())/new_data.shape[0])
            dict1.update(sub_dict)
            
            final_dict[col] = dict1
         
        else:
             final_dict[col] = dict((new_data[col].value_counts())/new_data.shape[0])
    return final_dict    

In [276]:
p_all_prob = get_probabilites(p_training_data)

In [277]:
e_all_prob = get_probabilites(e_training_data)

In [278]:
p_all_prob

{'cap-shape': {'x': 0.5489626556016598,
  'f': 0.42406639004149377,
  'b': 0.019087136929460582,
  'k': 0.007053941908713693,
  'c': 0.0008298755186721991,
  's': 0.0004139072847682119},
 'cap-surface': {'y': 0.4348547717842324,
  'f': 0.3153526970954357,
  's': 0.24813278008298756,
  'g': 0.0016597510373443983},
 'cap-color': {'g': 0.33526970954356844,
  'y': 0.27551867219917014,
  'n': 0.13817427385892117,
  'w': 0.13278008298755187,
  'b': 0.04979253112033195,
  'p': 0.036514522821576766,
  'e': 0.031950207468879666,
  'c': 0.00041322314049586776,
  'u': 0.00041322314049586776,
  'r': 0.00041322314049586776},
 'bruises': {'f': 0.7410788381742739, 't': 0.25892116182572616},
 'odor': {'f': 0.6887966804979253,
  'p': 0.10622406639004149,
  'c': 0.07966804979253111,
  'n': 0.046473029045643155,
  'y': 0.045228215767634854,
  's': 0.033609958506224065,
  'l': 0.00041339396444811904,
  'm': 0.00041339396444811904,
  'a': 0.00041339396444811904},
 'gill-attachment': {'f': 1.0, 'a': 0.00041

In [279]:
e_all_prob

{'cap-shape': {'x': 0.4849307629649742,
  'f': 0.4148791745859354,
  'b': 0.06978007059462395,
  'k': 0.021721422753190334,
  's': 0.008688569101276133,
  'c': 0.0002710761724044456},
 'cap-surface': {'y': 0.4018463209340212,
  'f': 0.38474070051588377,
  's': 0.21341297855009503,
  'g': 0.00027122321670735016},
 'cap-color': {'n': 0.28509367363562316,
  'g': 0.23893565028509367,
  'e': 0.1694270974748846,
  'w': 0.1566657616073853,
  'y': 0.10860711376595167,
  'b': 0.0130328536519142,
  'p': 0.0130328536519142,
  'c': 0.0065164268259571,
  'u': 0.004344284550638067,
  'r': 0.004344284550638067},
 'bruises': {'t': 0.7385283736084713, 'f': 0.26147162639152866},
 'odor': {'n': 0.7827857724680967,
  'a': 0.10860711376595167,
  'l': 0.10860711376595167,
  'c': 0.00027085590465872155,
  's': 0.00027085590465872155,
  'm': 0.00027085590465872155,
  'p': 0.00027085590465872155,
  'f': 0.00027085590465872155,
  'y': 0.00027085590465872155},
 'gill-attachment': {'f': 0.9994569644311703, 'a': 0

Calculating accuracy on cross validation data

In [336]:
cv_class = Cross_validation_data["class"]
cv_class

6093    p
6094    p
6095    p
6096    p
6097    p
6098    p
6099    p
6100    p
6101    p
6102    p
6103    p
6104    p
6105    p
6106    p
6107    p
6108    p
6109    p
6110    p
6111    p
6112    p
6113    p
6114    p
6115    p
6116    p
6117    p
6118    p
6119    p
6120    e
6121    p
6122    p
       ..
8094    e
8095    p
8096    e
8097    p
8098    p
8099    e
8100    e
8101    p
8102    e
8103    e
8104    e
8105    e
8106    e
8107    e
8108    p
8109    e
8110    e
8111    e
8112    e
8113    p
8114    p
8115    e
8116    p
8117    p
8118    p
8119    e
8120    e
8121    e
8122    p
8123    e
Name: class, Length: 2031, dtype: object

In [337]:
len(cv_class)

2031

In [344]:
cv_class.replace(to_replace=["p","e"], value=[1,0],inplace=True)

C:\Users\DELL\Anaconda3\lib\site-packages\pandas\core\generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [348]:
cv_class = np.array(cv_class)

In [349]:
cv_class

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [338]:
def posterior_probabilities(x):
    final_list=[]
    for ind in x.index:
        if i!=0:
            df = list(x.loc[ind])
            liklihood_p=1.0
            liklihood_e=1.0
            for d,col in zip(df,Cross_validation_data.columns[1:]):
                liklihood_p = liklihood_p  * p_all_prob[col][d]
                liklihood_e = liklihood_e  * e_all_prob[col][d]
            #print(liklihood_p,liklihood_e)
            posterior_p =(liklihood_p*prior_p_train)/((liklihood_p*prior_p_train)+(liklihood_e*prior_e_train))
            final_list.append(posterior_p)
       
    return np.array(final_list)
    #print(x[1])
    #liklihood_p =
    #liklihood_e
    

In [339]:
predicted_cv = posterior_probabilities(Cross_validation_data.iloc[:,1:])


In [340]:
predicted_cv

array([1.00000000e+00, 9.99999850e-01, 9.99998807e-01, ...,
       2.31914438e-04, 9.99999989e-01, 5.91705902e-03])

In [341]:
len(predicted_cv)

2031

In [342]:
predicted_cv = predicted_cv>0.5

In [343]:
predicted_cv

array([ True,  True,  True, ..., False,  True, False])

In [346]:
predicted_cv_val = np.uint(predicted_cv)

In [347]:
predicted_cv_val

array([1, 1, 1, ..., 0, 1, 0], dtype=uint32)

In [350]:
correct_count = np.count_nonzero(cv_class == predicted_cv_val)

In [351]:
correct_count

1875

In [353]:
cv_percent = (correct_count/Cross_validation_data.shape[0])*100

In [354]:
cv_percent

92.31905465288035

Calculating accuracy on testing data

In [355]:
testing_class = Testing_data["class"]

In [356]:
testing_class.replace(to_replace=["p","e"],value=[1,0],inplace=True)

C:\Users\DELL\Anaconda3\lib\site-packages\pandas\core\generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [358]:
testing_class_val = np.array(testing_class)

In [359]:
testing_class_val

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [360]:
predicted_testing = posterior_probabilities(Testing_data.iloc[:,1:])

In [361]:
predicted_testing 

array([9.27142632e-05, 5.07034530e-03, 5.09620863e-01, ...,
       2.31914438e-04, 9.99999989e-01, 5.91705902e-03])

In [362]:
predicted_testing_vla =np.uint( predicted_testing>0.5)

In [363]:
predicted_testing_vla

array([0, 0, 1, ..., 0, 1, 0], dtype=uint32)

In [364]:
testing_correct_count = np.count_nonzero(testing_class_val == predicted_testing_vla)

In [365]:
testing_correct_count

1078

In [366]:
testing_data_accuracy = (testing_correct_count/Testing_data.shape[0])*100

In [367]:
testing_data_accuracy

88.43314191960624